### ISSUE TITLE
WordPress 4.4 not using the custom title as expected

### ISSUE THREAD

**Issue by technical424** [gnotaras/wordpress-add-meta-tags#15] opened 2015-12-10 08:15 UTC
Hello

After latest worpress and plugin update all pages not showing custome title.

Its only showing description and meta tags.

thanks

**Comment by gnotaras** [comment] 2015-12-10 13:21
Hi,

I also replied in the wordpress forums, but I'm really glad you took the time to post your question here as well.

This tells me that I might have misjudged your message in the forums. I'm sorry if this is the case, but your message there had some characteristics I found alerting.

Isn't the title that appears on the page the expected title? Please let me know more details about this.

George

**Comment by gnotaras** [comment] 2015-12-10 13:26
As far as I can tell, the title appears correctly in your page.

The `title` element does not appear within the `<!-- [...] Add-Meta-Tags [...] -->` HTML comments, because we only filter its content.

Hope this helps.

George

**Comment by Muetze01** [comment] 2015-12-10 14:13
Hello (my English is not so good, but I hope you can understand me) ;-) , 
I have also the same problem as "technical24". My Title is not "correct", as I have written in my sites. The "Keywords & Description" ist perfect, but not the Titel. I made two Updates today, the Wordpress and yours. Afterwords the Title ist not the same, as I have in your "Add meta tag" on each site. There you have 3 Rows: Descript., Keyword & Title for each Site.
The answer you have given upside, I did not really understand. I´m also a Beginer in Wordpress. ;-) 
Sorry. ;-)   Perhaps you can help me?

Thank you. 
Michael

**Comment by gnotaras** [comment] 2015-12-10 15:07
Hi Michael,

Of course, I want to help, but I will need some information in order to locate the issue.

Please let me know what WP version are you running and which Add-Meta-Tags version is not working as expected regarding the custom titles? I assume you use WorDPress 4.3.1 and Add-Meta-Tags 2.9.11. Is this correct?

I'm marking this as a bug.

George

**Comment by gnotaras** [comment] 2015-12-10 15:13
Also, are there any PHP notices/errors logged in the error log about Add-meta-tags?

**Comment by Muetze01** [comment] 2015-12-10 15:23
Hello George,

I made an Update to WP-version 4.4 today and yours to 2.9.11

My Website is www.allesisteins.com  there you can see for example the 
Sub-site "Aktuell".
the *Title* NOW is "Aktuell", but befor (update) there was the Text 
(words) :
"Gemeinschaft, Ökodörfer, autark natürlich Leben, Gemüse, Wasser, Obst« 
Alles ist Eins"
in the 3rd Row.

Regards
Michael


Mit freundlichen Grüßen

Michael Rosenauer
089 / 20 33 58 84
(Freigeist & Querdenker)
Alles ist eins <http://www.allesisteins.com> - Ich freue mich auf Ihren 
Besuch.

Am 10.12.2015 um 16:13 schrieb George Notaras:

**Comment by gnotaras** [comment] 2015-12-10 15:39
Michael, are you referring to this page?  http://www.allesisteins.com/?page_id=466

Unfortunately, I cannot reproduce the problem in my test sites.

Since WordPress 4.4 contains some major changes regarding titles, also the themes might be affected. As far as Add-Meta-Tags is concerned, the issue has been resolved in 2.9.11 and there is really nothing more I can do. Of course, I'll continue to investigate it.

Would it be possible to test your web site with another theme, preferably one of the default themes, eg TwentyFifteen, and see if the problem persists?

Looking forward to your feedback.

George

**Comment by Muetze01** [comment] 2015-12-10 16:02
Emm ..... yes, for example this site. Now it will be shown (in 
SourceText for Google; yahoo) "Aktuell"

This "name" is given, when you create a new Sub-Site - but - with your 
Plugin, there is the possibility
you can override the "Title" in a Box and fill out the Boxes Description 
& Keywords.
So, I had Words in the Titel as: "*Gemeinschaft, Ökodörfer, autark 
natürlich Leben, Gemüse, Wasser, Obst« Alles ist Eins*"
This was shown until in the morning bevor I made the update (WP to 4.4 
and Your Meta .... 2.11.19)
And - since the update today I get again the "original Name" in Title 
(Aktuell), at the Creation-Time, but I want the
Words from your Meta-Data-Program as marked fat.
This mistake is on each Sub-Site, these are 17

Sorry, it is not possible to take another Theme, because my Theme is 
from Artisteer and from the year 2009. ;-)
So, this is my only one ;-)

Michael


Mit freundlichen Grüßen

Michael Rosenauer


Am 10.12.2015 um 16:39 schrieb George Notaras:

**Comment by gnotaras** [comment] 2015-12-10 16:21
> Sorry, it is not possible to take another Theme, because my Theme is from Artisteer and from the year 2009. ;-) So, this is my only one ;-)

In that case I am out of ideas about what else we could possibly try... I cannot reproduce the issue on my sites, while on the other hand it is not possible to say for sure what is the real cause of the problem in your web site's case: the theme or the plugin..

But, since your theme is that old (2009), I'd say it would be a good idea to contact the developer and point him to this page: https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/

BTW, installing and uninstalling a theme in WordPress is very easy. If you need help with this you can always ask for instructions in the wordpress org forums.

I'll follow this topic, but as of now, there is nothing more I can do about these cases.

George

**Comment by Muetze01** [comment] 2015-12-10 16:31
Thank you,

  but the Mistake is since today in the morning. Befor I made always 
updates and it runs perfectly.

Best regards
Michael



Mit freundlichen Grüßen

Michael Rosenauer


Am 10.12.2015 um 17:21 schrieb George Notaras:

**Comment by gnotaras** [comment] 2015-12-10 17:00
Michael, possibly I've found a solution that could be used in both old and new themes. I'll post more details shortly.

**Comment by Muetze01** [comment] 2015-12-10 17:07
Hello, hm, I don´t think, that a Theme make a problem, because I made 
the update from WP to 4.4 and not the Theme.

Thank you
Michael

Mit freundlichen Grüßen

Michael Rosenauer
089 / 20 33 58 84
(Freigeist & Querdenker)
Alles ist eins <http://www.allesisteins.com> - Ich freue mich auf Ihren 
Besuch.

Am 10.12.2015 um 18:00 schrieb George Notaras:

**Comment by gnotaras** [comment] 2015-12-10 17:12
Themes need to be updated for WP 4.4 as well, so I would recommend contacting the theme developer.

I'm just looking for a _workaround_ to make the plugin work in all cases. This is not a problem of the plugin. v2.9.11 should be considered fully compatible with Wordpress 4.4 and up to date themes

George

**Comment by Muetze01** [comment] 2015-12-10 17:41
Okay, thank you very much.

Best regards
Michael

Mit freundlichen Grüßen

Michael Rosenauer
089 / 20 33 58 84
(Freigeist & Querdenker)
Alles ist eins <http://www.allesisteins.com> - Ich freue mich auf Ihren 
Besuch.

Am 10.12.2015 um 18:12 schrieb George Notaras:

**Comment by gnotaras** [comment] 2015-12-10 18:54
Hi,

@Muetze01 and @technical424 

It turns out that it is essential to update your themes for WordPress 4.4. More specifically you have to enable the `title-tag` feature in the theme and remove any references to wp_title() in the `header.php` template.

The following should be considered as hints and not as a solution or instructions for a solution. Please ask a theme expert to implement this for you, if you think you do not have the necessary knowledge. Always keep backups of your files. Last but not least, you are responsible for any problems as a result of using the following info. I post them for informational purposes only.

Now that I've said this, the required changes are the following:

1. In the `functions.php` file of the theme, locate the `THEMENAME_setup()` function (THEMENAME varies according to the theme name) and add the following:

```php
add_theme_support( 'title-tag' );
```

For example:

```php

function twentytwelve_setup() {
    ...
    add_theme_support( 'title-tag' );
    ...
}
```

2. Locate the `header.php` file of your theme and remove the `title` tag altogether. For example in the TwentyTwelve theme, remove this:

```php
<title><?php wp_title( '|', true, 'right' ); ?></title>
```

Test whether the `title` element is populated correctly.

If you need more information about this, please use the wordpress org forums or other wordpress support channels.

There is nothing more I can do about this issue and, unfortunately, there is no official way to add support for all themes when used in WordPress 4.4.

However, if you notice anything wrong with the above hints, please feel free to post your feedback.

Kind Regards,
George

**Comment by gnotaras** [comment] 2015-12-11 19:06
Hi @Muetze01 and @technical424,

Version 2.9.12, which adds full backwards compatibility with older themes which don't use the `title-tag` theme feature under WordPress 4.4, has been released.

I will now close this issue. Your feedback is welcome.

George

**Closed by gnotaras** 2015-12-11 19:06 UTC
Labels: question

**Comment by lanterneRouge** [comment] 2016-02-23 17:38
Epic support - someone had to say so as the OP seems to have wandered off without saying thanks.

**Comment by gnotaras** [comment] 2016-02-27 05:55
@lanterneRouge I guess sometimes it happens that way. Thanks for the kind words. :)
