### ISSUE TITLE
Prefetch / Prerender on categories

### ISSUE THREAD

**Issue by joeyoungblood** [gnotaras/wordpress-add-meta-tags#31] opened 2016-02-01 06:35 UTC
I'm trying to install rel prerender and rel prefetch on category pages. When I go to edit them I notice the Yoast plugin is there but not the AMT plugin. I have everything deselected except for "Full meta tags box" and have done this on various other sites but not to category pages.

Is it possible to have this box on category pages? if so what am I missing?

**Comment by gnotaras** [comment] 2016-02-01 08:55
Hello Joe,

Thanks for your question.

A metabox, which would contain the 'Full Meta Tags' box, is not added to the category's (or other taxonomy term's) edit screen by Add-Meta-Tags. This is by design, but I'm open to ideas and suggestions about the implementation of such a feature, if it is needed.

However, taxonomy terms have standard characteristics and they lack the complexity of post objects, so full meta tags for taxonomy archives can be easily programmed. 

For instance, the following snippet will automatically add `prefetch` and `prerender` links for each post that exists in any archive page:

```php
function amt_add_prefetch_prerender_for_all_archive_posts( $metatags ) {
    if ( is_archive() ) {
        global $posts;
        if ( ! empty($posts) ) {
            foreach ( $posts as $post ) {
                $metatags[] = '<link rel="prefetch" href="' . get_permalink($post->ID) . '" />';
                $metatags[] = '<link rel="prerender" href="' . get_permalink($post->ID) . '" />';
            }
        }
    }
    return $metatags;
}
add_filter('amt_basic_metadata_head', 'amt_add_prefetch_prerender_for_all_archive_posts');
```

If you need this for category archives only, please replace `is_archive` with `is_category`.

This snippet can be added to the `functions.php` file of the theme or in a [plugin with customizations](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Cookbook_Snippet_Uses#Custom-Plugin). Now that I think about it, this could become a new feature (together with `prefetch` and `prerender` links for 'next' and 'previous' posts in content pages or 'next' and 'previous' pages of multipage content) which could be enabled in the plugin options.

About the metabox, my opinion is that a metabox for taxonomy terms would have to be built exclusively for this type of object, and, IMHO, apart from the 'full meta tags' field, I cannot think of any other attributes that I could add to it for customization. The archive titles can already be customized via defining title templates in `functions.php` (please read about the [Advanced Title Management](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Advanced_Title_Management) feature) and the description is taken directly from the term's description field.

I tried to wild guess about what exactly the links would point to. If anything else than the above snippet is needed, please let me know.

Kind Regards,
George

**Comment by joeyoungblood** [comment] 2016-02-01 11:15
Hi George,

Thanks for the incredibly thorough and well thought out response. I was under the impression that you could only Prerender / Prefetch one page per page, is that not the case?

A feature for prerender / prefetch would be awesome, but I was hoping - based on the belief I could only have one link prerender / prefecth per page - to specify a custom link based on either the typical user journey from Google Analytics or to prerender / prefetch the most valuable page such as the products page in an ecommerce funnel.

For most of my clients I add your plugin and use the full meta tags box to setup one prerender / prefetch link per page/post, but I have one client who uses only categories of posts with tons of customization to display content.

**Comment by gnotaras** [comment] 2016-02-01 18:53
Hi Joe,

> I was under the impression that you could only Prerender / Prefetch one page per page, is that not the case?

I'm sorry. I don't currently use this feature so I might be missing this specific limitation. I'll reply with more details as soon as I find some spare time to take a closer look.

> to specify a custom link based on either the typical user journey from Google Analytics or to prerender / prefetch the most valuable page such as the products page in an ecommerce funnel.

I see. In that case adding the prefetch/prerender links programmatically is definitely inconvenient, so I'll see if adding a metabox for taxonomy terms can be done without much effort or code modifications. I believe that most of the needed code is already there.

I'll reply very soon with more details.

George

**Comment by gnotaras** [comment] 2016-02-01 19:39
Just wanted to add that `prerender` links are not to be overused as they cause a full rendering (including linked resources) of the linked pages in the background, which in most cases is not a good thing. So, my snippet above is a *mistake* and should not be used.

I'll need some time to think about this.

George

**Comment by gnotaras** [comment] 2016-02-02 06:47
Joe, I've done some research about how this could be supported and the only resolution that makes sense is the addition of an AMT metabox in the taxonomy term edit screen, as you mentioned in the OP.

The box should include the following fields:

* 'Full meta tags' box for meta tags of the archive of the taxonomy term.
* 'Image URL' (a feature equal to the 'Global Image Override' of the metabox of the post edit screen), which would define the URL to an image for the taxonomy term.
* (Possibly) Field for custom keywords.
* (Possibly) Field for custom title.

If it is implemented, it will need to have the above fields.

BTW, I'm not testing any other plugin, so, if you have any other suggestions, please feel free to post them.

The implementation of this feature will definitely require some time. Currently some other features and fixes have higher priority, so the ETA might be days or weeks. I cannot really tell. This is a personal project of mine and the progress of development heavily depends on my free time.

Comments, corrections and suggestions are very welcome.

George

**Comment by joeyoungblood** [comment] 2016-02-04 02:30
I appreciate your work George, just update me when it's ready. I'm writing an article for my blog and then at least one other marketing website highlighting how to do this on WordPress sites. I might just omit the category / taxonomy feature for now.

**Comment by gnotaras** [comment] 2016-02-04 05:01
Thanks for letting me know Joe. I'm sorry for any inconvenience the delay might cause. I'll keep you updated.

**Comment by gnotaras** [comment] 2016-02-06 12:05
Hi Joe,

The feature has been implemented, but I still don't have an ETA for release. If testing goes well, I might make a new release within the weekend. It will be possible to enable the following extra fields for _term_ objects (categories, tags, terms of custom taxonomies) and for _user_ objects:

* Full meta tags box, supporting `meta` and `link` elements.
* Global image override (enforces the use of the specified image url in the metadata as the only image which overrides all other images that may have been attached to the object).

Some minor bugs have also been fixed and some minor extra features have been implemented.

Your feedback and ideas are very welcome. If you have any other suggestion for alternative implementation, please let me know (the sooner the better).

George

**Comment by joeyoungblood** [comment] 2016-02-06 14:52
Thanks George!

**Comment by gnotaras** [comment] 2016-02-08 09:54
Hello Joe, I will now close this issue as the feature has been implemented. Full meta tags fields will now be available in the term edit screen (category, tag, custom taxonomy) and in Wordpress user profiles.

Moreover, the special placeholder `PAGEINFO` (case sensitive) is now supported. This can be appended to URLs that exist within your custom meta tags. On the first page of multipage content or archives, this placeholder is just stripped. On subsequent pages, it is replaced with the proper page related path.

For instance, you can add the following meta tag in the edit screen of a taxonomy term:

```
<link rel="alternate" hreflang="fr" href="http://example.org/sections/multimedia/PAGEINFO" />
```

When evaluated, the URL will be as follows:

```
1st page of archive:  http://example.org/sections/multimedia/
2nd page of archive:  http://example.org/sections/multimedia/page/2/
3rd page of archive:  http://example.org/sections/multimedia/page/3/
```

Multipage content is also supported.

This feature can help create dynamic meta tags as far as paging is concerned.

I will now close this issue. If you have more suggestions, please feel free to add more comments or open a new issue.

Thank you very much for your feedback.

George

**Closed by gnotaras** 2016-02-08 09:54 UTC
Labels: enhancement, question

**Comment by evemilano** [comment] 2018-01-08 19:37
You should try this WP plugin https://www.evemilano.com/wp-prerender-plugin/ for dynamic prerender injection. It stores navigatinal paths in the databse and creates a meta tag prerender with the most probable next visited page. It works fine for me.
