### ISSUE TITLE
Title issue (No title shown at all)

### ISSUE THREAD

**Issue by its-thomas** [gnotaras/wordpress-add-meta-tags#4] opened 2015-10-14 18:49 UTC
Hi George!

Refering to the issue from the following thread: https://wordpress.org/support/topic/bug-custom-title-issue-not-fixed-in-250?replies=7

It is not working anymore, which has probably to do with update 2.9.3. and the "Re-added the %title% tag expansion functionality in the custom title. (props to ndrwpvlv for feedback)" issue (as far as I can assume).

With my pages, there is now a blank where the page title should be, followed by "|" (without quotes) and the site title.... doesn't look very good.

You think you might be able to fix this issue?

Thomas

**Comment by gnotaras** [comment] 2015-10-14 19:02
Hello Thomas, I'll look into this ASAP.

In the mean time, here you can find older [Add-Meta-Tags releases](http://www.codetrax.org/projects/wp-add-meta-tags/files), but I think I'll be able to provide a workaround very soon.

**Comment by gnotaras** [comment] 2015-10-14 19:21
I'm going to need some feedback, because it's been a long time and a lot of things have changed.

I assume you use the following code in `functions.php`:

```php
function amt_custom_title_modified( $title ) {
    return $title . ' | ';
}
add_filter( 'amt_custom_title', 'amt_custom_title_modified', 10, 1 );
```

Could you please *comment out* this code, visit a post and let me know of the content of the `<title>` HTML element?

Also, is there any reference of `wp_title` in the child or parent theme's `header.php` or `functions.php`?

**Comment by its-thomas** [comment] 2015-10-14 19:30
You are right, I am using the code you mentioned. With the code commented out, I have the same problems again as mentioned in the wordpress.org thread: Page title is followed by site title without any space or "|".

Header.php (child and parent theme) mentions:
```
wp_title( '|', true, 'right' );
```

Hope this helps :-)

**Comment by gnotaras** [comment] 2015-10-14 19:40
> Page title is followed by site title without any space or "|".
> Header.php (child and parent theme) mentions:
>     wp_title( '|', true, 'right' );

I cannot tell what could possibly cause this issue. It is most probably related to the theme, but a plugin could also interfere in the title generation.

Could you try using this modified workaround instead?

```php
function amt_custom_title_modified( $title ) {
    if ( empty($title) ) {
        return '%title% | ';
    } else {
        return $title . ' | ';
    }
}
add_filter( 'amt_custom_title', 'amt_custom_title_modified', 10, 1 );
```

**Comment by its-thomas** [comment] 2015-10-14 19:50
The modified workout seems to have fixed it "almost"! The only issue I can still make out is that pages without a custom title have two "|" between page and site title. Is this fixable?

**Comment by gnotaras** [comment] 2015-10-14 19:57
> The only issue I can still make out is that pages without a custom title have two "|" between page and site title. Is this fixable?

Please try the following:

```php
function amt_custom_title_modified( $title ) {
    if ( empty($title) ) {
        return '%title%';
    } else {
        return $title . ' | ';
    }
}
add_filter( 'amt_custom_title', 'amt_custom_title_modified', 10, 1 );
```

Please re-check posts with and without a custom title.

**Comment by its-thomas** [comment] 2015-10-14 20:02
Solved! :-)

Great service as usual, George!

Thanks so much!

**Comment by gnotaras** [comment] 2015-10-14 20:12
Thomas, thanks for letting me know! :-)

Please, keep in mind that this is just a workaround. This particular filter hook is not meant to be used to add any formatting, such as a ` | `, to the title. Hopefully, the above snippet will work fine as is for a long time, because no further changes are planned in this area, but you will definitely have to investigate what causes the issue with the page title and the site name being printed together without a separator in the `<title>` element.

**Comment by its-thomas** [comment] 2015-10-14 20:33
I see

> but you will definitely have to investigate what causes the issue with the page title and the site name being printed together without a separator in the title element.

I use WordPress Twenty Eleven theme, just to let you know.

**Comment by gnotaras** [comment] 2015-10-14 22:16
OK, I'll leave this issue open for now and, as soon as I get some free time in the following days, I'll try to do some testing. Also, if you use any plugin that could interfere with the title generation, please let me know about it as well.

Thanks for your feedback!

**Comment by gnotaras** [comment] 2015-10-15 19:25
I'm looking into this right now. The TwentyEleven theme does the following processing in the `header.php` template:

```php
<title><?php
    // Print the <title> tag based on what is being viewed.
    global $page, $paged;

    wp_title( '|', true, 'right' );

    // Add the blog name.
    bloginfo( 'name' );

    // Add the blog description for the home/front page.
    $site_description = get_bloginfo( 'description', 'display' );
    if ( $site_description && ( is_home() || is_front_page() ) )
        echo " | $site_description";

    // Add a page number if necessary:
    if ( ( $paged >= 2 || $page >= 2 ) && ! is_404() )
        echo esc_html( ' | ' . sprintf( __( 'Page %s', 'twentyeleven' ), max( $paged, $page ) ) );

    ?></title>
```

The Add-Meta-Tags _Custom Title_ functionality completely replaces the `wp_title()` output with the custom title, as it has been entered by the user in the Metadata box in the post editing screen. If any extra processing takes place in the `header.php` template, like it happens in the TwentyEleven theme, Add-Meta-Tags cannot possibly replace the full content of the `<title>` HTML element, because it cannot edit the template.

The suggested solution is to use the following in the `header.php` template:

```php
<title><?php wp_title( '|', true, 'right' ); ?></title>
```

Apart from this, the workaround I posted earlier can be used:

```php
function amt_custom_title_modified( $title ) {
    if ( empty($title) ) {
        return '%title%';
    } else {
        return $title . ' | ';
    }
}
add_filter( 'amt_custom_title', 'amt_custom_title_modified', 10, 1 );
```

The ` | ` separator should be replaced with the separator used in `wp_title()` in the `header.php template.

I could mark this as a bug, but its not really an issue of the plugin, since it is impossible for it to edit the code of the template file.

Also, I'd like to point out the new [Advanced Title Management](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Advanced_Title_Management) functionality as a way to have total control over the generated titles throughout the web site.

**Comment by its-thomas** [comment] 2015-10-15 20:09
Hi George :-)

So, I assume that as long as I use your "Add Meta Tags" plugin, I can safely ditch the workaround and instead replace the whole large chunk of title-code that comes with twenty eleven theme header template with the following single line:

```<title><?php wp_title( '|', true, 'right' ); ?></title>```

Which is also what you would recommend, am I right?

**Comment by gnotaras** [comment] 2015-10-15 21:28
For a new web site, I'd say that using the following in `header.php` is the way to go:
'''
<title><?php wp_title( '|', true, 'right' ); ?></title>
'''
For your current website, I highly recommend going ahead with using the aforementioned workaround. Making the change in `header.php` would affect the title of current posts, which have a custom title, because the ` | Site Name` part would not be added any more to the custom title.

**Comment by gnotaras** [comment] 2015-10-15 21:30
I'll keep this ticket open and do some more research about how this could be resolved cleanly. I highly recommend that you keep using the workaround for the time being. I'll let you know if I figure out a solution that works in all cases.

**Comment by its-thomas** [comment] 2015-10-15 21:44
Ok, I'll stick with the workaround. Besides that: I really don't want you to take all that workload on you because of me! I am sure the workaround will do just fine for the time being and longer!

Thanks so much for all you have done already!

**Comment by gnotaras** [comment] 2015-10-15 21:46
No worries. This is something that needed to be done at some point.

**Comment by gnotaras** [comment] 2015-10-16 00:26
Hi Thomas,

I did some testing. This is not a bug. There is no clean way to make it work in themes in which further processing of the title takes place outside the `wp_title()` function like it happens in TwentyEleven.

Also, the _Advanced Title Management_ feature is not going to work as expected in similar themes. I've updated the [theme requirements](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Requirements) of the plugin.

/moreover, here is a simpler version of the workaround:

```php
function amt_custom_title_modified( $title ) {
    if ( ! empty($title) ) {
        return $title . ' | ';
    }
}
add_filter( 'amt_custom_title', 'amt_custom_title_modified');
```

I *highly recommend* to continue using the workaround for the reason I mentioned earlier. Using the workaround should be fine for a long time.

However, in new web sites, I highly recommend populating the `<title>` HTML element in the `header.php` template like this:

```
<title><?php wp_title( '|', true, 'right' ); ?></title>
```

Or adding title support to the theme (check TwentyFifteen) like this:

```
add_theme_support( 'title-tag' );
```

If you try the new version of the workaround, please let me know if it works as expected.

This post should be considered final for this issue. I'll leave this ticket open for some more days and then close it.

It was in my plans to do this kind of testing. Thank you for all the feedback. It has been very helpful.

Kind Regards,
George

**Comment by its-thomas** [comment] 2015-10-16 07:34
The simpler version of the workaround seems to work just fine! Just tested it!

Thanks :-)

**Comment by gnotaras** [comment] 2015-10-16 08:57
OK. I'm going to close this topic then. Thanks for your feedback! :-)

**Closed by gnotaras** 2015-10-16 08:57 UTC
Labels: question
