### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by daniushko** [gnotaras/wordpress-add-meta-tags#26] opened 2016-01-17 14:58 UTC
Hi George,

I'm sorry for bothering you again, but I can't cope with something simple. I have a meta description to most of my pages and galleries already. Unfortunately when I test the site with a toll the description is not visible. I'tr tried many tools and all they see only the title and the keywords, but not the description. Please advice me where I'm wrong!

Thanks,

Daniel

**Comment by gnotaras** [comment] 2016-01-17 19:45
Hi Daniel,

I checked the HTML source code of various pages of http://swansphotography.com (the domain name was visible in the screenshot in #25) and indeed I don't see any description meta tags or any meta tags that could have been generated by Add-Meta-Tags.

This can happen for a number of reasons:

1. You use a page caching plugin, caching proxy or CDN and the cached pages have not been refreshed after activating Add-Meta-Tags. In this case please clear all caches.
1. No metadata generators have been enabled in the Add-meta-tags settings.
1. The theme does not meet the [requirements](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Requirements#Metadata-Generation) for metadata generation.

I'm not sure what the problem is in this case. But taking into account that data from the site-wide meta tags box appeared on your website, I don't think there is a problem with your theme, but instead I'd say to double check if there are any page caches involved.

Hope this helps.

Kind Regards,
George

**Comment by daniushko** [comment] 2016-01-17 20:14
Hi George,

Thank you very much for your quick and ind response! I'm really impressed.
Por my shame it seems it's the second reason that cause the problem. I wasn't aware I have to choose any of the settings in order yo make the description appear.  I thought it's for advanced users and I left it for the time when I'd have more experience. I did a test with basic one and it's OK now.

Thank you very much!

Daniel

**Comment by gnotaras** [comment] 2016-01-17 21:50
No problem, Daniel. Glad you have sorted it out!

I'll now close this issue. Please feel free to post more feedback if needed.

Kind Regards,
George

**Closed by gnotaras** 2016-01-17 21:50 UTC
Labels: question

**Comment by daniushko** [comment] 2016-01-17 22:07
efharisto kala poli ":)

**Comment by gnotaras** [comment] 2016-01-18 16:38
Daniel, you are welcome! :)
