### ISSUE TITLE
Problem with title and microdata of EDD

### ISSUE THREAD

**Issue by Mihai751** [gnotaras/wordpress-add-meta-tags#17] opened 2015-12-18 00:37 UTC
The EDD plugin adds "itemprop" span fields to a products title page to hold microdata. 
The problem is then that Add Meta tags doesn't filter out these span tags and the meta tag for title includes them. 

EDD support told me that I should contact you to suggest that you instead of using get_the_title in your plugin, you should be using the_title_attribute which strips out any html from the title name.

**Comment by gnotaras** [comment] 2015-12-18 02:42
Hello Mihai,

Thank you for your feedback. I'll look into this issue and try to resolve it for the next release.

Currently, my free time is very limited to work on improving support for EDD, but any hints from the EDD support team are greatly appreciated.

Kind Regards,
George

**Comment by gnotaras** [comment] 2015-12-18 05:32
Hi,

I've fixed this issue for the next release. The fix involved enclosing `get_the_title()` in `strip_tags()` instead of using the `the_title_attribute()`. I'd appreciate if you could confirm with the EDD support that this is an equivalent fix as far as EDD is concerned, provided that `esc_attr()` is used when adding the title to the meta tags.

Thanks in advance.

George

**Comment by Mihai751** [comment] 2015-12-18 06:14
Hello George,

Thank you for your quick reply and resolution on this! Is there a reason 
why you choose not to switch the use of "get_the_title" with 
"the_title_attribute", which already strips tags of the title? I am by 
no means an expert in WP, just wondering what the reason is so I can 
relay it to the EDD staff.

Cheers,
Mihai

**Comment by gnotaras** [comment] 2015-12-18 07:54
Hi Mihai,

The reason is basically that it seemed cleaner for me. Also, from what I read `the_title_attribute()` also calls `strip_tags()`, so I thought of using it directly.

BTW, I'm able to provide a beta version with this issue fixed, but I'm a little hesitant because you said you do not feel expert with WP. Do [these](https://wordpress.org/support/topic/metadata-review-mode-problem?replies=16#post-7793888) sound complicated?

If you would like to wait for the final release, that is perfectly fine and actually the wise thing to do. :)

George

**Comment by gnotaras** [comment] 2015-12-18 08:49
I've also fixed an issue which I noticed that existed with the _Advanced Title Management_ feature, which didn't return the title to the metadata generators in case a _title template_ had not been found. I haven't included it yet in any beta release.

On a second thought, I might postpone some features implementations and fixes for another release and release 2.10.3 today. It has some minor but necessary improvements and it's definitely better than 2.10.2.

**Comment by Mihai751** [comment] 2015-12-18 09:50
Hi,

As I have a live site I prefer not to install a beta according to those 
instructions (even though they are perfectly clear and it's not 
complicated), so I think for most people they would prefer the official 
2.10.3 release.

Yes, I also noticed the problem with the title not appearing at all when 
turning on Advanced Title Management. It would be great to have that 
working but I see no reason to delay .3 for it.

Cheers!
Mihai

**Comment by gnotaras** [comment] 2015-12-18 10:43
This is perfectly fine! 2.10.3 is almost ready. The issue you mentioned and also the one I noticed with EDD and _Advanced Title Management_ have been fixed.

_Advanced Title Management_ needs a title template in order to have any effect. I haven't added default title templates for EDD yet, but will happen soon. If you ever need help to add your own title templates, please let me know.

I will now close this issue. Thanks for all your feedback!

George

**Closed** 2015-12-18 10:43 UTC
Labels: bug, needs-feedback

**Comment by gnotaras** [comment] 2015-12-18 11:09
OK there it is.. I added a [section with sample _title templates_ for EDD](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Advanced_Title_Management#Easy-Digital-Downloads). Please also read the information in this page to better understand how it is done. This page needs more work. If you ever have any questions, please let me know.

They should work with 2.10.2, but I'd suggest waiting for the 2.10.3 before experimenting with them.

Also, please note that EDD is not fully supported yet. The generated metadata is not very detailed yet for complex products. I'll need more time to get more familiar with EDD for such improvements.

Best Regards,
George

**Comment by gnotaras** [comment] 2015-12-19 01:30
I had to delay 2.10.3 for a while in order to investigate another small issue that I encountered with EDD's category/tag archives when the JSON+LD schema.org generator was enabled.

This has now been addressed and I will release 2.10.3 shortly.

**Comment by gnotaras** [comment] 2015-12-19 05:41
Hi Mihai,

As far as I can tell 2.10.4 has the best support for EDD so far. We are not there yet regarding metadata for complex products, but this is in the TODO list. I hope that it is fine for now.

Now, I cannot reproduce any of the aforementioned problems any more. Your feedback is welcome.

Kind Regards,
George

PS: I usually neglect the marketing part, but I'd like to say that, if you like this plugin, a small review is always much appreciated and is actually a great motivation to keep up with the development. On the contrary, if there are things you do not like, please send your feedback and all issues will be resolved in their good time. Sometimes development can be slow, because I do this in my free time, but I have a personal interest in meeting my web sites' needs so I keep improving this plugin constantly.

**Comment by Mihai751** [comment] 2015-12-20 14:06
Hi,

I've checked out the new version now and things seem fine! I've tried 
the custom title templates too and they seem to be working ok as well. 
I'm on WP 4.4. There is a small error in the docs code for the EDD example:

|add_filter('amt_titles_metadata_title_templates','amt_titles_custom_metadata_title_templates_for_edd'
|


Missing parenthesis and semi-colon. I've also added the #site_name# part 
to some of the template rows for the EDD metadata version which weren't 
there.

Thanks for your quick replies and solutions, I've also made a donation 
for your plugin and I'll make sure to leave a review soon.

Thanks again!
Mihai

**Comment by gnotaras** [comment] 2015-12-21 07:46
Hello Mihai,

Thank you very much for donating to the project and also for considering a review. It is much appreciated!

I've corrected the typos in the sample customization snippet. I had copied the snippet from the PuTTY screen while working on my server's console and had missed the two last characters. Thanks for pointing it out!

Please note that the sample title templates that exist on that page are meant to be used as examples in order to get users started with title template customization. There are different title templates for the title that is generated for the `title` HTML element and for the title that is used in the metadata (eg the `og:title`, `twitter:title` meta tags) for maximum flexibility. In general, in these sample templates the site name (`#site_name#` template variable) has been intentionally omitted from the title templates that are used in the meta tags, since this piece of information  is usually included in the shared item in the social network's timeline, but of course it is a good extra addition to the object's title in many cases. Please customize the titles as you see fit. If you need any help with it, please let me know.

Also, I intend to improve the EDD support during the upcoming months. I would have done this already, but currently I do not use this plugin so I need to get a little more familiar with its logic. Your feedback is welcome.

Best Regards,
George

**Comment by gnotaras** [comment] 2015-12-21 12:33
Just wanted to let you know that I took a closer look at EDD's options regarding variable prices/products (on the free version). It seems simple enough, so full support for variable products might come a little sooner than I had initially planned. Really good plugin.

George

**Comment by gnotaras** [comment] 2015-12-22 11:10
Hello Mihai, I've opened issue #19 for open discussion about the EDD support in AMT. If you have more feedback and suggestions about how the support for EDD should be improved, please post it in there. Thanks in advance!

Best Regards,
George
