### ISSUE TITLE
hreflang in Full Meta Tags

### ISSUE THREAD

**Issue by zephyr88** [gnotaras/wordpress-add-meta-tags#38] opened 2016-02-18 17:44 UTC
I used to have these in my Full Meta Tags box, for example.

```
<link rel="alternate" hreflang="en" href="http://www.astrasuite.com/astrablog/neodio-origine-s1-by-hk-on-cc/" />
<link rel="alternate" hreflang="en-ID" href="http://www.lyrics-soundart.com/lyrics-news/neodio-origine-s1-by-hk-on-cc/" />
```

And it worked, Metadata review shows it.  Now, it does not show, on any post.  The rest of Add Meta Tags stuff show though

Thanks, please help

**Comment by gnotaras** [comment] 2016-02-18 20:35
Hi @zephyr88 

I could not replicate the issue. I added the exact same link elements in the _Full Meta Tags_ box of a post and they showed up as expected in the metadata.

The only thing that might have changed is the fact that the algorithm now groups all `hreflang` links together.

Since I'm unable to reproduce theproblem, I'll close this issue. Feel free to reopen it and provide more feedback.

Kind Regards,
George

**Closed by gnotaras** 2016-02-18 20:35 UTC
Labels: question
