### ISSUE TITLE
404 error on all pages after installing the plugin

### ISSUE THREAD

**Issue by ifproject** [gnotaras/wordpress-add-meta-tags#20] opened 2015-12-23 15:19 UTC
After plugin installation all the navigation of the website is not workng and no single page is found anymore, either as ?post=xxxx or with permalink

Permalinks options are ok and .htaccess file is ok, saved it again as /%postname%/ but no changes

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /main/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /main/index.php [L]
</IfModule>

Another misbehaviour after installation is if I publish a page the preview shows alert you don't have privileges to view draft pages (!). If the pages are draft a 404 error is returned

Could you please help asap as I was ready to publish a fuly functional website and now after instaling the plugin and not even editing any keywords or description everything is screwed up.

Wordpress version  is 4.1

Thanks

**Comment by gnotaras** [comment] 2015-12-23 15:47
Hi,

I wish I could help, but there is no way I can explain how the plugin could possibly cause the problems you have described above. This plugin basically uses the `wp_head`, `wp_footer` action hooks, and the `the_content` filter hook to print some metadata in the HTML source and also uses the standard API to add a metabox in the post editing screen in order to be able to customize this metadata.

I'd need some more information that relates the problem to my plugin, please.

First, I'd suggest to fully log out from the web site and clean the web browser cache. There is a possibility that some error message pages have been cached by your web browser. Please clean the cache and re check the web site.

Secondly, I would suggest to deactivate Add-Meta-Tags and make sure your web site works as expected.

After you have confirmed the web site is running as expected, then reactivate Add-Meta-Tags and please re-check your web site.

If you notice any misbehavior or errors, please provide me with any error messages that have been recorded in the web server's error log and in the php error log (if you keep a separate log for php errors).

BTW, are these the standard `.htaccess` rules that are generated by wordpress? Does you wordpress run inside the `/main/` subdirectory?

The 404 errors and the error messages about privileges are not caused by this plugin, unless a very weird and extraordinary customization has been done. Has the core plugin files been edited by you or other person?

One thing is certain: Add-Meta-Tags has not screwed your web site. Just deactivate it and it's gone. All its data/settings/cache can be cleared from the command line using `wp-cli`. Please let me know so I can provide detailed instructions.

Looking forward to your feedback with more details.

Kind Regards,
George

**Comment by gnotaras** [comment] 2015-12-23 15:52
> RewriteBase /main/
> ...
> RewriteRule . /main/index.php [L]

I'm not sure if the above `RewriteRule` is correct. Has this been generated by WP? Where is `.htaccess` located? Inside `/main/`?

I'd suggest replacing the rewrite rule with:

```
RewriteRule . /index.php [L]
```

George

**Comment by ifproject** [comment] 2015-12-23 16:09
Hi george, thankyou for your detailed reply. Yes the site run inside the /main directory in the developement phase and the .htaccess code is correct, it is generated by wp.
Thanks also for explaining how the plugin works, this will help me to troubleshoot further the issue. It could be unrelated with the plugin but it showed up immediately after the installation.

I'll let you know.

Many thanks for your support.

**Comment by gnotaras** [comment] 2015-12-23 16:21
Hi, thanks for your reply. In general, add-meta-tags is a simple plugin and does not do any weird things. Your feedback is welcome!

George

**Comment by ifproject** [comment] 2015-12-23 17:28
Hi George, problem solved and as you thought the plugin wasn't the culprit, it looks like a weird browser cache problem, I had to reboot to solve it.

Finally I can get my hands on add-meta-tags settings...

Thank you very much for your support.

**Comment by gnotaras** [comment] 2015-12-23 19:34
Hi, thanks for letting me know. It has happened to waste much time with something similar in the past. There is the possibility that the response http headers of wordpress' error messages might play a role in the caching of the redirects or the error pages by the browser. Never investigated it any further..

Anyway, glad you have sorted it out. I'm going to close this issue. I'll also add the 'invalid' label, but this is only for categorization so as to easily tell which issue was an actual bug. You did very well and reported the problem you encountered.

Kind Regards,
George

**Closed by gnotaras** 2015-12-23 19:34 UTC
Labels: needs-feedback, question
