### ISSUE TITLE
Default Image Height Width

### ISSUE THREAD

**Issue by webeau** [gnotaras/wordpress-add-meta-tags#27] opened 2016-01-20 21:42 UTC
Google Schema Testing Tool complains that height and width are required with image and are missing.  When you select a default image using an absolute url no height or width is provided which generates errors.

Better to be able to pick an image from the media library where height and width can be provided or to have a way to enter this information so it can be used in the schema markup.

Posts with images also have height and width correctly added.  This only effects posts or pages without a featured image causing the plugin to use the default image.

**Comment by gnotaras** [comment] 2016-01-21 10:22
Thanks for your feedback.

A ticket about the improvement of this particular area exists in my personal bug tracker since a long time ago and I guess the time has come to take a closer look at it.

First of all, a decision has to be made about what should be filled in the _default image_ field in the plugin settings. There are two options:

1. The post ID of the image attachment, which will then be used by the plugin at run time to get the relevant information for the metadata.
1. A special notation that will include the image's width and height.

Since I try to maintain backwards compatibility as much as possible, I tend to think that option 2 is much better for backwards compatibility and also for performance. Your feedback about this is much appreciated.

My initial intention was to support a special notation, like:

```
URL[,WIDTHxHEIGHT][,TYPE]
```

width/height/type should be optional.

To make it a little easier, an image selector from the media library, which would fill in the special notation automatically in the _default image_ field in the plugin settings would be nice. But, I'll need some time for testing and research to implement it in a secure way without reinventing the wheel. Any help is much appreciated.

I had taken a note of [this code snippet](https://gist.github.com/gnotaras/04eec43ebc3f536b60ab) a while ago.

Another option would be to also use the site's icon, if one exists, but I also need to do some research about it.

What are your thoughts?

George

**Comment by gnotaras** [comment] 2016-01-21 10:29
BTW, Google's Structured Data Testing Tool does not show me these errors yet (checking from Greece).

**Comment by gnotaras** [comment] 2016-01-22 17:22
After taking a closer look at it, my intention is to add support for everything that has been mentioned in an as clean as possible way. However, implementation and testing might take a while.

**Comment by webeau** [comment] 2016-01-24 00:27
Hello George,

Sorry for the delay.  I appreciate your comments.  I am not sure why the Google Structured Data Testing Tool would no show these errors where you are.  Here the errors state that Height and Width are required although, looking at the spec. at schema.org for Article, I don't think they are required.  At the same time, these pages are showing up on my Google Webmaster Tools with the structured data now and there are no reported errors but they still show errors when I look at the testing tool.  Perhaps that is a problem with the testing tool as Google's other tools and the specification don't seem to require these fields.

**Comment by gnotaras** [comment] 2016-01-24 00:41
Hi Bret,

Thanks for the update. I guess Google enables the new validation rules gradually and they'll show up here as well in a few days (delays have happened before).

I'm going to reopen the issue, since this is something that had to be done anyway, so this is a good opportunity.

George

**Comment by gnotaras** [comment] 2016-02-04 17:10
Hey Bret, I'm going to release 2.10.8 with some improvements. This feature will be delayed at least until 2.10.9. I'm sorry for any inconvenience.

**Comment by raymondpirouz** [comment] 2016-02-05 16:42
Hi guys, I experienced the same issue and thought I would add some more context for you by providing a screenshot of the error as shown by Google -- hope this helps illustrate further:

![width-height](https://cloud.githubusercontent.com/assets/17086762/12852536/6e7bda26-cbfd-11e5-94f5-1a62e86e7d41.JPG)

**Comment by gnotaras** [comment] 2016-02-06 12:07
Hi @raymondpirouz 

Thanks for the screenshot. I'm not sure if this feature will be finally implemented for the next release, but some required work for it has been done as part of the implementation of #31, so it will be definitely easier for me now. I'll keep you updated.

**Comment by gnotaras** [comment] 2016-02-06 14:33
By the way, I just re-tested this by connecting to the Google Structured Data Tool service via a server in New York and via another one in Frankfurt, Germany, but I still I cannot replicate the validation errors.

Raymond, may I ask what part of the website the above screenshot corresponds to? Is this a post? Also, what image is used?

**Comment by gnotaras** [comment] 2016-02-06 14:39
Oh, I found the post and figured it out. This post does not have an image attached, so the default image from the plugin settings is most probably used. The problem is that, when checking the front page, which also uses the same default image, no validation errors are displayed despite the lack of `width` and `height` attributes. Hmm...

Nevertheless, I'm working on the fix. (Requires more work than I had initially thought as some refactoring is needed!)

**Comment by webeau** [comment] 2016-02-06 14:57
Are the front page and post schema types the same?  Posts are articles on my site and it is within those that I get an error.  The front page is usually webpage or localbusiness or similar.

**Comment by gnotaras** [comment] 2016-02-06 16:01
@webeau They are exactly as you described, but the default image is used as a fallback image in case another image cannot be found in all parts of the website. The inconsistency of the validator is that for the same `ImageObject` which lacks width and height attributes, it does not report any errors on the home page, but does report errors on posts. At least this is what I noticed. Anyway, it does not make any difference. This will be fixed globally.

**Comment by raymondpirouz** [comment] 2016-02-06 16:06
Yes, sorry @gnotaras the specific error is in response to this code snippet as I understand it:


<span itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
<meta itemprop="name" content="Stream of Consciousness logo" />
<meta itemprop="text" content="Stream of Consciousness logo" />
<meta itemprop="url" content="http://soc.raymondpirouz.com/wp-content/uploads/2016/01/rp_square.png" />
<meta itemprop="contentUrl" content="http://soc.raymondpirouz.com/wp-content/uploads/2016/01/rp_square.png" />
</span> 

And it -- I believe -- is generated as a result of this setting in the WP back end via your plug-in: "Default Image: Enter an absolute URL to an image that represents your website, for instance the logo."

If I remove the link in that field and refresh, rechecking using Google's tool, I get an error saying the image is required. When I re-insert the link and check again, I get the error indicating that width and height are not specified.

Hope that helps, and thanks for the quick reply!

P.S. I can definitely confirm the fact that the error ONLY RESULTS on pages that do not use featured images, thereby falling back to the default logo I specified using your plugin back-end as stated above (and as you figured out!). So I think the solution (among many probably) might be to include width and height of image fields on the back end so I can input them and your code can insert them....or whatever other elegant solution you come up w/is fine also.  :)  Excellent plug-in.

**Comment by gnotaras** [comment] 2016-02-06 16:22
Hello Raymond, thank you for the detailed feedback and the kind words! :)

The solution is the following: Any field that expects an image URL will also support:

1) The following special notation (optional parts are in brackets):

```
URL[,WIDTHxHEIGHT]

For example:

http://example.org/images/logo.png,1024x768
```

The `WIDTHxHEIGHT` part is optional. From the example above the plugin will figure out the URL of the image, the image type and the dimensions. 

2) An ID (integer), which is the ID of an image attachment that has been uploaded to the media library. Of course, there will be a button that could be used to select the image from the media library and auto insert its ID (the implementation of the button might be delayed for one release). In this case all image attributes are retrieved from WordPress.

This way backwards compatibility is maintained and at the same time it is possible to generate metadata for all the basic image attributes provided that the user enters the relevant dimensions.

If you have any better idea, suggestion or correction, please feel free to post it!

George

**Comment by raymondpirouz** [comment] 2016-02-06 17:23
That sounds perfect to me @gnotaras -- thanks.

**Comment by gnotaras** [comment] 2016-02-08 10:00
Hi all, the aforementioned functionality has been implemented at a low level, but for various reasons the implementation of an image selection button has been left for the next release (very soon). I will now close this issue. Nevertheless, please feel free to add more comments.

Raymond, thank you very much for donating to the project. It is much appreciated! :)

Best Regards,
George

**Closed by gnotaras** 2016-02-08 10:00 UTC
Labels: enhancement

**Comment by gnotaras** [comment] 2016-02-08 11:41
BTW, if an attachment ID is entered in any field that expects an image URL, there is currently a known issue caused by a WordPress sanitization function which prepends the scheme 'http(s)://' to it. This will be fixed as soon as the image selection dialog is implemented..
