### ISSUE TITLE
Question about meta descriptions

### ISSUE THREAD

**Issue by zeldamar** [gnotaras/wordpress-add-meta-tags#34] opened 2016-02-03 14:20 UTC
Hi!  I'm fairly new to wordpress and your great plugin. 

 I have a question - I seem to be getting two descriptions when I view my source code.  One is the title and the other is the description.  
Do I have something set up incorrectly?  I tried turning off auto generate descriptions but that didn't seem to help.

I've attached a file showing my values for the page and the source code.

Thanks so much for your help.

[pdf file removed]

**Comment by gnotaras** [comment] 2016-02-03 17:21
Hi zeldamar,

Thanks for your kind words!

Add-Meta-Tags (AMT) generates a single `description` meta tag, which does not contain the title, and this is regardless of the configuration. The generated metadata is enclosed in [HTML comments](http://www.codetrax.org/attachments/215). Any meta tag outside these HTML comments is generated by another plugin or by the theme, in which case I'm afraid I cannot provide any help.

BTW, I'd appreciate it if you uploaded screenshots instead of PDF files. I removed the attached file and to be honest I didn't check it. Please re-upload a screenshot if your want a general opinion about the issue.

Kind Regards,
George

**Comment by zeldamar** [comment] 2016-02-03 18:48
George;
I'm attaching screen shots so you can see my issue.
Thanks for your speedy reply.
Meta1 is the page source.  Meta2 is my set up.  See that it's using the title as the 2nd description.
![meta1](https://cloud.githubusercontent.com/assets/17046990/12793083/bda346fc-ca7c-11e5-8bb5-cdef1718274b.JPG)
![meta2](https://cloud.githubusercontent.com/assets/17046990/12793084/bda45c04-ca7c-11e5-9781-02260e5b6a33.JPG)

**Comment by gnotaras** [comment] 2016-02-04 00:43
Hi zeldamar,

Thank you for the screenshots.

First, a small remark about the keywords. It would be good practice to separate the keywords with commas (enter a comma delimited list of keywords) and also to keep the number of keywords to the absolute minimum keywords to describe the topic of the page.

Also, another remark about the `rel="icon"` link, the `href` attribute of which is missing a second slash in the beginning. It should be `href="//wp-conte...`.

About the meta data, according to the above settings, the expected result would be:

* A single `description` meta tag inside the 'Add-Meta-Tags' HTML comments which would contain your custom description. This exists.
* A single `keyword` meta tag inside the 'Add-Meta-Tags' HTML comments which would contain your custom keywords. This exists.
* A single title HTML element (`<title>`) which would contain your custom title alone (*Your cost effective solution*). This is where there is a problem. The title HTML element does not contain the custom title. Moreover, the custom title appears inside a `description` meta tag outside the AMT HTML comments. The cause of this issue is not my plugin, but most probably the `header.php` template of the theme.

It would be very helpful if there was a screenshot of your theme's `header.php` template which would show how the title element and the first description meta tag are populated. The theme does not seem to be following the best practices in this area, but instead the theme developer tried to implement something that is very much incomplete. I recall that I had encountered a similar issue in the past. Although this is outside the scope of the support for the AMT plugin, if you could provide me with a screenshot of the beginning of the `header.php` template, I could possibly help you fix the problem.

George

**Comment by gnotaras** [comment] 2016-02-04 04:57
btw, @zeldamar, I just noticed that the issue was closed. I'm now reopening it. Please feel free to post your feedback.

George

**Comment by zeldamar** [comment] 2016-02-04 11:42
George;
Thanks for all the information.  Here is the screen shot.  The theme I am using is a cherry framework.  So I think it uses this header.php
![meta3](https://cloud.githubusercontent.com/assets/17046990/12814081/60deacac-cb0a-11e5-8c8e-2a1b8e8af660.JPG)
Thanks again for you assistance.

**Comment by gnotaras** [comment] 2016-02-04 12:15
Exactly as I had thought.. This is an OK way to populate the `title` element and the `description` meta tag, but **not a good way**, if you are using a plugin that takes care of these.

My suggestions:

1) Replace the entire `<title> ... </title` block (multiple lines) with:

```
<title><?php wp_title( '|', true, 'right' ); ?></title>
```

2) Delete completely the line that hard codes the `description` meta tag (the one that contains the `wp_title()` function). This is not needed and actually adding the title inside the description is a weird habit..

This line:

```
<meta name="description" content="<?php wp_title(); echo ..... />
```

Please make sure you keep a backup of the file (eg: `header.php.backup`)

George

**Comment by gnotaras** [comment] 2016-02-04 12:29
Also, please note that changing the titles of your content could possibly lead to a temporary slight change of the positions of your pages in search results. There is no general rule, but it depends on the wqeb site and how established it is.

But, if you want to do this right in order to utilize the features of Add-Meta-Tags or other similar plugins, then these changes in the theme template have to be done.

**Comment by gnotaras** [comment] 2016-02-04 17:06
Hi zeldamar,

I'm cleaning up the existing issues for the upcoming release and I'll close this one. Nevertheless, please feel free to post more feedback or even re-open the issue. By following the instructions I posted earlier the problems should be fixed.

George

PS: I usually neglect the marketing part, but if you like this plugin, a review at wordpress org at any time is always much appreciated! :)

**Closed by gnotaras** 2016-02-04 17:06 UTC
Labels: question

**Comment by zeldamar** [comment] 2016-02-08 23:38
George;

Thanks so very much for your help.

I was able to edit the file as you suggested and it worked perfectly!!

 

Thank you very much for you great plug in and your above and beyond assistance.

 

Pat

**Comment by gnotaras** [comment] 2016-02-09 05:51
Hi Pat, very glad that the solution worked!

George
