### ISSUE TITLE
Wrong Parameter count For....

### ISSUE THREAD

**Issue by Rocket-Boy** [gnotaras/wordpress-add-meta-tags#32] opened 2016-02-01 08:19 UTC
Hi,

singe the Last Update i get the error Message:
Warning: wrong parameter count for array_uniqe() in ....... /plugins/add-Meta-Tag/metadaten/amt_basic.php on line 250

Plugin Version is: 2.10.7
After deaktivate the plugin, error doesn't appears

Please help

**Comment by Rocket-Boy** [comment] 2016-02-01 08:25
Sorry, the Plugin version is: 2.10.7.

**Comment by gnotaras** [comment] 2016-02-01 09:06
Hi there,

Thanks for your feedback.

As far as I can tell, there is nothing wrong with this line of code. But this could happen due to an older PHP version (eg 5.2) that is being used. Could you please check it with your hosting provider and let me know about the PHP version?

I'll add a check about it in the next release. Thanks for letting me know.

Kind Regards,
George

**Comment by gnotaras** [comment] 2016-02-01 09:13
Until the next release is out, you can safely comment out this line to avoid getting this PHP warning.

Line 250 of `add-meta-tags/metadata/amt_basic.php` should become:

```php
//    $robots_options = array_unique( $robots_options, SORT_STRING );
```

Hope this helps.

George

**Comment by Rocket-Boy** [comment] 2016-02-02 15:08
Hi George,

thanks for advice, commt out the line works.
PHP Version: 5.2.6-1+lenny3

Thx
Mirko

**Comment by gnotaras** [comment] 2016-02-02 15:12
> PHP Version: 5.2.6-1+lenny3

Hi Mirko, I thought so. I'll add a check in the next release. The problem is the second argument (flag) of the `array_unique()` function which is not supported in PHP 5.2.X.

Thank you for your feedback!

George

**Comment by gnotaras** [comment] 2016-02-04 16:13
Fixed. I'll now close this issue. Thanks for your feedback.

George

**Closed by gnotaras** 2016-02-04 16:13 UTC
Labels: bug, resolved
